fragment actionUpdatedFeed on PlannerActionSetWrapper {
  dataSetEditChanges(filters: {locale: $defaultLocale}) {
    updatedFeed(first: $first, after: $after) {
      totalCount
      edges {
        node {
          id
          newValue {
            ...basicDetailsItem
          }
          updatedColumnData {
            ...updatedColumnDataItem
          }
        }
      }
      pageInfo {
        ...pageInfoFields
      }
    }
  }
}

fragment updatedColumnDataItem on UpdatedColumnData {
  gradeScaleId
  columnName
  oldValue
  newValue
}
