fragment organizationResourceItem on OrganizationResource {
  id
  label
  state
  item {
    ... on Assignment {
      id
      deadline
      contentType
      state {
        state
        publishedAt
      }
      content {
        id
        ... on Assessment {
          ...assessmentItem
        }
      }
    }
    ... on OrganizationResource {
      id
      attachment {
        ...attachmentItem
        type
        title
      }
    }
  }
  attachment {
    ...attachmentItem
    type
    title
  }
}

fragment assessmentItem on Assessment {
  id
  type
  title {
    id
    value
  }
  assessmentType {
    id
    value
  }
  taskType {
    id
    type
    label
  }
  image {
    id
    value
  }
  category {
    id
    label
  }
  fields(uids: ["subjectLevel"]) {
    id
    uid
    value
  }
}
