fragment attachmentItem on Attachment {
  id
  name
  type
  mimeType
  url
  signedUrl
  thumbUrl
  title
  metadata
  streamUrl
  parentType
  isRead
  similarityReport {
    ...similarityItem
  }
  childAttachments {
    id
    type
  }
  createdBy {
    id
    type
  }
  lockingState {
    state
    scheduledAt
  }
  questionAttachment {
    ... on QuestionSubmission {
      id
      questionScore
      score {
        id
        value
      }
    }
    ... on Question {
      id
      questionScore
    }
  }
}
