fragment collectionItem on OrganizationResourceConnection {
  resourceTypeBasedCount {
    totalCount
  }
  edges {
    node {
      id
      label
      type
      resourceType
      metadata
      entity {
        id
        ...subjectItem
      }
      childrenV2(filters: $postFilters) {
        resourceTypeBasedCount {
          totalCount
        }
        edges @skip(if: $skipPostData) {
          node {
            id
            label
            type
            resourceType
            entity {
              id
              ...subjectItem
            }
            item {
              id
              ...learnerPortfolioPostItem
            }
          }
        }
      }
    }
  }
}
