mutation createAndMapAcademicSubjectLevelToSchools($input: CreateAndMapAcademicSubjectLevelToSchoolsInput!) {
  platform {
    createAndMapAcademicSubjectLevelToSchools(input: $input) {
      isSuccess
      warning
      subjectLevel {
        id
        uid
        label
        abbreviation
        reportDisplayName
        displaySequence
        type
        curriculumProgram {
          id
          programType
        }
        childLevels {
          id
          curriculumProgram {
            id
          }
        }
      }
      mapped {
        schoolCurriculumProgramId
        childLevelId
      }
    }
  }
}
