mutation createPost($courseId: ID, $title: String, $description: String, $createdBy: ID!, $unitPlanId: ID, $resourceId: ID, $resourceType: FLOW_SECTION_ITEM_ENUM, $elementsPYP: [PYPElement!], $attachments: [AttachmentInput!], $studentIds: [ID!], $state: PostStateEnum!, $publishedBy: ID!, $isPrivate: Boolean, $isHiddenFromStudents: Boolean, $folders: [ID!], $folderNames: [String!], $practicesV2: PostPracticeCreateInput, $curriculumProgramId: ID, $parentId: ID, $parentType: POST_ITEM_TYPE_ENUM, $academicYears: [ID!], $ibPYPElementRatings: [IBPYPElementRatingInput!], $isStudentIndividuallyRated: Boolean, $learnerPortfolioResource: OrganizationResourceGroupInput) {
  documentation {
    createPost(input: {courseId: $courseId, title: $title, description: $description, createdBy: $createdBy, unitPlanId: $unitPlanId, resourceId: $resourceId, resourceType: $resourceType, elementsPYP: $elementsPYP, attachments: $attachments, studentIds: $studentIds, state: $state, publishedBy: $publishedBy, isPrivate: $isPrivate, isHiddenFromStudents: $isHiddenFromStudents, folders: $folders, folderNames: $folderNames, practicesV2: $practicesV2, curriculumProgramId: $curriculumProgramId, parentId: $parentId, parentType: $parentType, academicYears: $academicYears, ibPYPElementRatings: $ibPYPElementRatings, isStudentIndividuallyRated: $isStudentIndividuallyRated, learnerPortfolioResource: $learnerPortfolioResource}) {
      id
      __typename
    }
    __typename
  }
}
