fragment documentCategoryHelpText on SnPDocumentCategory {
  id
  i18nHelpText(filters: {locale: $locale}) {
    ... on HelpText {
      ...helpTextDetails
    }
  }
}

fragment attachmentEvidenceItem on Attachment {
  id
  type
  title
  streamUrl
  url
  signedUrl
  name
  mimeType
  thumbUrl
  description
  metadata
  resolvedParentEntity {
    ... on AttachmentGroup {
      resolvedParentEntity {
        ... on StudentAssignmentSubmission {
          id
          assignment {
            id
            assignedStudents {
              id
              submission {
                id
              }
            }
          }
        }
      }
    }
  }
}
