fragment studentItem on Student {
  id
  calendarEvents(filters: $filters) {
    id
    startTime
    endTime
    itemType
    item {
      id
      ... on Assignment {
        ...assignmentItem
      }
      ... on CalendarEventItem {
        ...calendarEventItem
      }
      ... on CalendarEvent {
        ...calendarEvent
      }
      ... on ProjectDeadline {
        ...projectDeadline
      }
    }
    calendars {
      id
      parentType
      parent {
        ... on Course {
          ...courseItem
        }
      }
    }
  }
}

mutation generateStudentFamilyInviteReport($status: [FamilyMemberStatusEnum!], $filters: GenerateStudentFamilyInviteReportFilterInput, $fileName: String) {
  platform {
    generateStudentFamilyInviteReport(input: {status: $status, filters: $filters, fileName: $fileName}) {
      url
    }
  }
}

mutation generateStudentFamilyInviteReport($status: [FamilyMemberStatusEnum!], $filters: GenerateStudentFamilyInviteReportFilterInput, $fileName: String) {
  platform {
    generateStudentFamilyInviteReport(input: {status: $status, filters: $filters, fileName: $fileName}) {
      url
    }
  }
}
