query getAnnouncementRecipientsFeed($announcementId: ID!, $academicYearId: ID!, $first: Int, $after: String, $filters: CircularRecipientsFeedFilters, $withSubtext: Boolean = false, $organizationId: ID) {
  node(id: $announcementId, type: CIRCULAR) {
    id
    ... on Circular {
      sharedWith
      recipientsFeed(input: {academicYearId: $academicYearId, first: $first, after: $after, filters: $filters}) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          cursor
          node {
            id
            isRead
            user {
              id
              firstName
              middleName
              lastName
              type
              profileImage
              email
              ... on Student {
                id
                prefix
                suffix
                pronouns
                preferredName
                alertTypes {
                  ...alertTypeFields
                }
                yearGroup @include(if: $withSubtext) {
                  id
                  grade {
                    id
                    name
                  }
                }
              }
              ... on Staff {
                id
                prefix
                suffix
                pronouns
                preferredName
                displayRole @include(if: $withSubtext)
              }
              ... on FamilyMember {
                id
                prefix
                suffix
                pronouns
                preferredName
                children(organizationId: $organizationId) @include(if: $withSubtext) {
                  id
                  firstName
                  lastName
                  middleName
                  preferredName
                  prefix
                  pronouns
                  suffix
                  sourceId
                }
              }
            }
          }
        }
      }
    }
  }
}
