query getAccountEventTypesWithEventsFeed($input: CalendarEventTypesFeedInput!) {
  platform {
    calendarEventTypesFeed(input: $input) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          label
          colorCode
          parentEventTypeId {
            id
          }
          associatedEvents(input: {first: 30, filters: {createdAtLevel: ACCOUNT}}) {
            totalCount
            pageInfo {
              hasNextPage
              endCursor
            }
            edges {
              node {
                id
                label
                isFullDayEvent
                startDateTime
                endDateTime
                eventTag {
                  id
                  label
                  colorCode
                }
                parentEvent {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
