query getPublishedNodesTaggedInDataFromNodeSetQuery($id: ID!, $nodesFilters: PlannerElementNodeFilters, $nodeCountFilters: DataSetNodeCountWrapperFilters, $shouldSkipAssessment: Boolean! = false, $shouldSkipPortfolio: Boolean! = false, $shouldSkipUnitPlan: Boolean! = false, $shouldSkipStudentProgressReport: Boolean! = false, $isParentTaggingEnabled: Boolean! = false) {
  node(id: $id, type: PLANNER_ELEMENT_NODE_SET) {
    ... on PlannerElementNodeSet {
      id
      plannerElementNodeSetWrapperV2 {
        ... on PlannerElementNodeSetWrapper {
          publishedData(filters: $nodesFilters) {
            edges {
              node {
                ...dataSetNodeCountWrapperFragment
              }
            }
          }
        }
        ... on PlannerBenchmarkSetWrapper {
          publishedData(filters: $nodesFilters) {
            edges {
              node {
                ...dataSetNodeCountWrapperFragmentPyp
              }
            }
          }
        }
      }
    }
  }
}

query getAiConverstion($id: ID!) {
  node(id: $id, type: AI_CONVERSATION) {
    ... on AiConversation {
      id
      messages {
        totalCount
        edges {
          node {
            id
          }
        }
      }
    }
  }
}

query getAiConverstion($id: ID!) {
  node(id: $id, type: AI_CONVERSATION) {
    ... on AiConversation {
      id
      messages {
        totalCount
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
