query getAssignmentsMappedToGrades($id: ID!, $grades: [ID!], $academicCriteriaSetsFilter: academicCriteriaSetsFilter, $assignmentFeedFilters: AssignmentFeedFilters, $assessmentFilters: AssessmentFilters) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      constants {
        academicCriteriaSets(grades: $grades, filters: $academicCriteriaSetsFilter) {
          id
          label
          isShowGradeBoundaries
          academicCriteriaValues {
            id
            assessments(filters: $assessmentFilters) {
              id
            }
            assignments(filters: $assignmentFeedFilters) {
              id
            }
          }
        }
      }
    }
  }
}
