query getAIVoiceTonesForCurriculum($organizationId: ID!, $curriculumIds: [ID]) {
  node(id: $organizationId, type: ORGANIZATION) {
    id
    ... on Organization {
      curriculumPrograms(curriculumIds: $curriculumIds) {
        id
        voiceTones {
          ...aiVoiceTone
        }
      }
    }
  }
}

mutation updateAiContextCategoryUserPreferenceForProgressReport($input: UpdateAiContextCategoryUserPreferenceInputs!) {
  documentation {
    updateAiContextCategoryUserPreferenceForProgressReport(input: $input) {
      isSuccess
    }
  }
}
