query getAITutorAwardsReview($id: ID!) {
  node(id: $id, type: ASSESSMENT) {
    id
    ... on Assessment {
      id
      assessmentTools {
        edges {
          node {
            id
            assessmentToolType
            isTeacherEvaluationEnable
            isStudentEvaluationEnable
            assessmentToolItem {
              id
              ... on StandardRubric {
                ...standardRubricItem
              }
            }
          }
        }
      }
      aiConversation {
        edges {
          node {
            id
            entitySubType
          }
        }
      }
      ibPYPElementRatings {
        id
        ibPYPElementType
        value
        metadata
      }
      toolResponsesV2(filters: {userFilter: ALL}) {
        id
        toolId
        toolType
        toolResponses {
          ...toolResponseItem
        }
      }
      aiTutorAwardEntry {
        ...aiTutorAwardEntryReview
      }
    }
  }
}

query getAiConverstion($id: ID!) {
  node(id: $id, type: AI_CONVERSATION) {
    ... on AiConversation {
      id
      messages {
        totalCount
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
