query getAllCurriculumClasses($curriculumProgramId: ID!, $curriculumInterfaceType: ENTITY_TYPE_ENUM!, $filters: CurriculumProgramConnectionsFilters) {
  node(id: $curriculumProgramId, type: $curriculumInterfaceType) {
    id
    ... on IbPypCurriculumProgram {
      id
      classes(first: 10000, filters: $filters) {
        edges {
          node {
            id
            title
          }
        }
      }
    }
    ... on IbMypCurriculumProgram {
      id
      classes(first: 10000, filters: $filters) {
        edges {
          node {
            id
            title
          }
        }
      }
    }
    ... on UBDCurriculumProgram {
      id
      classes(first: 10000, filters: $filters) {
        edges {
          node {
            id
            title
          }
        }
      }
    }
    ... on IbDpCurriculumProgram {
      id
      classes(first: 10000, filters: $filters) {
        edges {
          node {
            id
            title
            subjectGroups {
              ...subjectGroupBasicDetailsItem
            }
          }
        }
      }
    }
  }
}
