query getBehaviourIncidentFeed($id: ID!, $input: BehaviourIncidentFeedInput, $accessibleUsersInput: BehaviourAccessibleUsersInput!, $includeAccessibleUsers: Boolean = false) {
  node(id: $id, type: ORGANIZATION) {
    ... on Organization {
      id
      behaviourIncidentFeed(input: $input) {
        totalCount
        stateWiseCount {
          draft
          published
          resolved
        }
        pageInfo {
          endCursor
          hasNextPage
        }
        edges {
          node {
            ...incidentDetails
            ... on BehaviourIncident {
              id
              accessibleUsers(input: $accessibleUsersInput) @include(if: $includeAccessibleUsers) {
                userType
                sharedWithUser
                totalCount
              }
            }
          }
        }
      }
    }
  }
}
