query getCPGradeBookProjectGroupProjects($id: ID!, $projectGradeBookFilters: ProjectGroupProjectsFilters, $projectFieldFilters: PlannerFieldFilter, $academicYearId: ID, $isGroupSubmissionMode: Boolean!) {
  node(id: $id, type: PROJECT_GROUP) {
    ... on ProjectGroup {
      id
      projects(filters: $projectGradeBookFilters) {
        totalCount
        pageInfo {
          endCursor
          hasNextPage
        }
        edges {
          node {
            ...gradeBookInfo @include(if: $isGroupSubmissionMode)
            ...individualGradeBookInfo @skip(if: $isGroupSubmissionMode)
          }
        }
      }
    }
  }
}
