query getCourseFlowStaffList($id: ID!, $collaboratorFilters: LearningCourseCollaboratorFilters) {
  node(id: $id, type: LEARNING_COURSE) {
    id
    ... on LearningCourse {
      id
      collaborators(orderBy: FULL_NAME, filters: $collaboratorFilters) {
        edges {
          node {
            id
            firstName
            middleName
            lastName
            preferredName
            prefix
            suffix
            pronouns
            profileImage
            isArchived
          }
        }
      }
    }
  }
}
