query getCurriculumDepartments($id: ID!, $curriculumInterfaceType: ENTITY_TYPE_ENUM!, $filters: SubjectGroupFilterInput) {
  node(id: $id, type: $curriculumInterfaceType) {
    ... on IbPypCurriculumProgram {
      id
      subjectGroups(filters: $filters) {
        ...subjectGroupBasicDetailsItem
        subjects {
          id
          name
        }
      }
    }
    ... on IbMypCurriculumProgram {
      id
      subjectGroups(filters: $filters) {
        ...subjectGroupBasicDetailsItem
        subjects {
          id
          name
        }
      }
    }
    ... on UBDCurriculumProgram {
      id
      subjectGroups(filters: $filters) {
        ...subjectGroupBasicDetailsItem
        subjects {
          id
          name
        }
      }
    }
    ... on IbDpCurriculumProgram {
      id
      subjectGroups(filters: $filters) {
        ...subjectGroupBasicDetailsItem
        subjects {
          id
          name
          type
        }
      }
    }
  }
}
