query getClassesList($id: ID!, $coursesFilters: CourseFilterInput, $first: Int, $after: String, $orderBy: ORDER_BY_ENUM, $orderByDirection: ORDER_BY_DIRECTION) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      courses(filters: $coursesFilters, first: $first, after: $after, orderBy: $orderBy, orderByDirection: $orderByDirection) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            id
            title
            primaryGrade {
              id
              name
            }
          }
        }
      }
    }
  }
}
