query getCoursesFeed($organizationId: ID!, $filters: LearningCourseFilters, $after: String) {
  node(id: $organizationId, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      learningCourses(first: 20, after: $after, filters: $filters) {
        edges {
          node {
            id
            title
            isArchived
            academicYears {
              id
              startDate
              endDate
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}
