query getDashboardAlerts($id: ID!, $input: DashboardAlertFilterInput) {
  node(id: $id, type: ORGANIZATION) {
    ... on Organization {
      id
      analytics {
        dashboardAlerts(filter: $input) {
          totalCount
          edges {
            id
            insightDashboardId
            dashboard_name
            alertFrequency
            alertSchedule
            weekDay
            createdAt
            subscribers {
              id
              firstName
              middleName
              lastName
              email
              profileImage
            }
            createdBy {
              id
              firstName
              lastName
              middleName
            }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }
  }
}
