query getLearningCourseDetails($id: ID!, $filters: LearningCourseCollaboratorFilters, $rnpFilters: RnPRoleContextDetailFilterInput, $classesFilters: LearningCourseClassFilter, $gradeFilters: LearningCourseGradeFilters) {
  node(id: $id, type: LEARNING_COURSE) {
    id
    ... on LearningCourse {
      id
      ...learningCourseItem
      classes(filters: $classesFilters) {
        id
        title
        sourcedId
        profileImageData {
          url
          icon
          color
          acronym
        }
        curriculumProgram {
          id
          type
          nodeInterfaceType
          label
          acronym
        }
      }
      collaborators(filters: $filters) {
        edges {
          node {
            id
            type
            profileImage
            firstName
            lastName
            middleName
            preferredName
            prefix
            suffix
            pronouns
            isDevUser
            rnpRoleContextDetail(filters: $rnpFilters) {
              id
              contextType
              role {
                id
                label
              }
              context {
                id
              }
            }
          }
        }
      }
    }
  }
}
