query getOrganizationCoursesQuery($organizationId: ID!, $first: Int, $after: String, $filters: CourseFilterInput) {
  node(id: $organizationId, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      courses(first: $first, after: $after, orderBy: TITLE, orderByDirection: ASC, filters: $filters) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            id
            title
          }
        }
      }
    }
  }
}
