query getOrganizationCourseUsersV3($organizationId: ID!, $first: Int, $after: String, $filters: CourseFilterInput, $skipStudents: Boolean = true, $skipStaff: Boolean = true, $skipFamilyMembers: Boolean = true, $includeCurriculumPrograms: Boolean = true) {
  node(id: $organizationId, type: ORGANIZATION) {
    ... on Organization {
      id
      courses(first: $first, after: $after, filters: $filters) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            id
            title
            grades {
              id
              name
            }
            curriculumProgram {
              id
              label
            }
            profileImageData {
              icon
              color
              acronym
              url
            }
            students @skip(if: $skipStudents) {
              edges {
                node {
                  ...userDetailItemV2
                }
              }
            }
            collaborator @skip(if: $skipStaff) {
              edges {
                node {
                  ...userDetailItemV2
                }
              }
            }
            familyMembers @skip(if: $skipFamilyMembers) {
              edges {
                node {
                  ...userDetailItemV2
                }
              }
            }
          }
        }
      }
    }
  }
}
