query getOrganizationDPSubjects($id: ID!, $filters: SubjectFilterInput) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      subjects(filters: $filters) {
        id
        name
        icon
        grades {
          id
          name
          globalGrade {
            id
            uid
          }
        }
        contentSubject {
          id
          assessmentYearTitle
        }
        ibOfferedSubject {
          id
          contentSubject {
            id
            assessmentYearTitle
            assessmentYearEndsOn
          }
        }
        isArchived
        flatVariants {
          isArchived
          level {
            id
            label
            globalTag {
              id
            }
          }
          responseLanguage {
            id
            label
            globalTag {
              id
            }
          }
        }
        subjectGroup {
          id
          name
          type
        }
        variants {
          level {
            id
            label
          }
          responseLanguages {
            id
            label
          }
        }
      }
    }
  }
}
