query getOrganizationYearGroupsForAcademiYearTransition($id: ID!, $filters: YearGroupFilter) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      yearGroups(filters: $filters) {
        ...basicYearGroupDetails
      }
    }
  }
}

fragment yearGroupAcademicYearMapDetails on YearGroupAcademicYearMap {
  academicYear {
    id
    isCurrentAcademicYear
    isUpcomingAcademicYear
    isPreviousAcademicYear
  }
  yearGroup {
    id
    name
    curriculumProgram {
      id
      acronym
    }
  }
}
