query getOrganizationTeachers($organizationId: ID!, $archivalState: ARCHIVAL_STATE_ENUM, $curriculumProgramIds: [ID!], $academicYearIds: [ID!], $first: Int, $after: String, $searchText: String) {
  node(id: $organizationId, type: ORGANIZATION) {
    ... on Organization {
      id
      staff(filters: {archivalState: $archivalState, curriculumProgramIds: $curriculumProgramIds, academicYearIds: $academicYearIds, searchText: $searchText}, first: $first, after: $after) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            id
            ...staffNameFields
            profileImage
            email
          }
        }
      }
    }
  }
}
