query getOrganizationStaffFeed($first: Int, $after: String, $filters: OrgConnectionFilterInput, $orderBy: ORDER_BY_ENUM, $orderByDirection: ORDER_BY_DIRECTION) {
  platform {
    organization {
      id
      staff(first: $first, after: $after, filters: $filters, orderBy: $orderBy, orderByDirection: $orderByDirection) {
        pageInfo {
          endCursor
          hasNextPage
        }
        edges {
          node {
            id
            email
            firstName
            middleName
            lastName
            preferredName
            prefix
            suffix
            pronouns
            profileImage
            type
          }
        }
      }
    }
  }
}
