query getOrganizationCourses($organizationId: ID!, $courseFilters: CourseFilterInput) {
  node(id: $organizationId, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      courses(orderBy: TITLE, orderByDirection: ASC, filters: $courseFilters) {
        edges {
          node {
            id
            title
            subjects {
              id
            }
            primaryGrade {
              id
            }
            allCollaborators {
              edges {
                node {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
