query getOrganizationAssessments($id: ID!, $first: Int, $after: String, $filters: AssessmentOrganizationFilters, $uids: [String!]) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      assessments(first: $first, after: $after, filters: $filters) {
        totalCount
        pageInfo {
          hasNextPage
          startCursor
          endCursor
        }
        edges {
          node {
            ...assessmentItem
            createdBy {
              id
              firstName
              lastName
              profileImage
            }
            unitPlan {
              id
              image {
                id
                value
              }
            }
          }
        }
      }
    }
  }
}
