query getOrganizationStudentsFeed($first: Int = 10, $after: String, $filters: OrgConnectionFilterInput, $orderBy: ORDER_BY_ENUM, $orderByDirection: ORDER_BY_DIRECTION) {
  platform {
    organization {
      id
      students(first: $first, after: $after, filters: $filters, orderBy: $orderBy, orderByDirection: $orderByDirection) {
        totalCount
        pageInfo {
          endCursor
          hasNextPage
        }
        edges {
          node {
            id
            email
            firstName
            middleName
            lastName
            pronouns
            preferredName
            prefix
            suffix
            profileImage
            alertTypes {
              ...alertTypeFields
            }
            yearGroup {
              name
              id
            }
            sourceId
            type
            isBlocked
          }
        }
      }
    }
  }
}
