query getOrganizationAcademicYearsForGradingHistory($id: ID!, $termFilters: TermFilters) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      academicYears {
        id
        startDate
        endDate
        terms(filters: $termFilters) {
          id
          label
          abbreviation
          type
          lockingStatus
          associatedAcademicTermEntities {
            id
            academicTerm {
              id
              type
            }
            cumulativeAcademicTermWeightages {
              id
              weightage
              percentage
            }
          }
        }
      }
    }
  }
}
