query getOrganizationSubjectGroups($id: ID!, $filters: SubjectGroupFilterInput, $subjectFilters: SubjectFilterInput) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      subjectGroups(filters: $filters) {
        id
        name
        globalSubjectGroup {
          id
          constants
        }
        subjects(filters: $subjectFilters) {
          id
          name
          icon
          grades {
            id
            name
          }
          ibOfferedSubject {
            id
            contentSubject {
              id
              assessmentYearTitle
            }
          }
        }
        sourceSubjects {
          id
          name
        }
      }
    }
  }
}
