query getProjectGroupStudentsWithPortfolios($id: ID!, $studentFilters: ProjectGroupStudentFilters, $studentProjectPortfolioFilter: StudentProjectPortfolioFilter, $academicYearId: ID) {
  node(id: $id, type: PROJECT_GROUP) {
    ... on ProjectGroup {
      id
      students(filters: $studentFilters) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            id
            student {
              ...projectGroupStudentsItem
            }
          }
        }
      }
    }
  }
}
