query getProductUpdatesFeedDetails($filters: ProductUpdatesFilterV2, $orderBy: ORDERBY_FIELD_ENUM_CMS, $onlyNewContent: Boolean) {
  cms {
    productUpdatesFeedV2(filters: $filters, orderBy: $orderBy, onlyNewContent: $onlyNewContent) {
      edges {
        node {
          ...productUpdateItem
          __typename
        }
      }
    }
    __typename
  }
}

fragment identityPermissionsConfigurationV2Item on ConfigurationV2 {
  id
  uidV2
  configuration
  valueType
  value
  isLocked
  description
}
