query getPointSystemConfiguration($id: ID!) {
  node(id: $id, type: CURRICULUM_PROGRAM) {
    ... on CurriculumProgram {
      id
      label
      type
      acronym
      logo
      pointSystemConfiguration {
        id
        isEnabled
        isStudentBalanceEnabled
        startingBalance
        resetSchedule
        canAddPoints
        canContributeToBalance
        isNegativeBalanceAllowed
        visibleToStudent
        visibleToFamily
        updatedAt
        updatedBy {
          id
          ... on Staff {
            firstName
            middleName
            lastName
            preferredName
            prefix
            suffix
            pronouns
          }
        }
      }
    }
  }
}
