query getPublishedStandardSetCounts($id: ID!, $filters: PlannerElementNodeFilters, $isPYPCurriculum: Boolean! = false) {
  node(id: $id, type: PLANNER_ELEMENT_NODE_SET) {
    ... on PlannerElementNodeSet {
      id
      standardSetWrapper {
        publishedStandards(filters: $filters) @skip(if: $isPYPCurriculum) {
          edges {
            node {
              ...plannerElementNodeCountItem
            }
          }
        }
        publishedBenchmarks(filters: $filters) @include(if: $isPYPCurriculum) {
          edges {
            node {
              ...plannerBenchmarkCountItem
            }
          }
        }
      }
    }
  }
}

fragment notificationItem on Notification {
  id
  type
  primaryEntity
  isNew
  isRead
  metadata
  category
  createdBy {
    id
    firstName
    lastName
    middleName
    profileImage
    type
    profileImage
    ... on Student {
      preferredName
      pronouns
      suffix
    }
  }
  createdAt
  updatedBy {
    id
    firstName
    lastName
    middleName
    profileImage
    ... on Student {
      preferredName
      pronouns
      suffix
    }
  }
  course {
    ...courseItem
    grades {
      id
      name
    }
    curriculumProgram {
      id
      type
    }
  }
  courses {
    id
    title
    curriculumProgram {
      id
      type
    }
  }
  updatedAt
  contextData {
    ... on Grade {
      id
      name
    }
    ... on Course {
      id
      title
      learningCourse {
        id
        title
        academicCourse {
          id
          label
        }
      }
    }
    ... on YearGroup {
      id
      name
    }
    ... on Student {
      id
      firstName
      lastName
      middleName
      type
      preferredName
      pronouns
      suffix
    }
    ... on BehaviourIncident {
      id
      uid
      category {
        id
        rootCategory {
          id
          name
        }
      }
    }
  }
  messageData
  extensionType
  extensionData
}
