query getRoutineBasicDetails($id: ID!, $filter: RoutineFilterOptions!) {
  node(id: $id, type: ORGANIZATION) {
    id
    ... on Organization {
      id
      curriculumPrograms {
        id
        routines(filter: $filter) {
          id
          label
          routineMode
          dayPatternType
          startDate
          endDate
          grades {
            id
            name
          }
          rotationDays {
            id
            label
            abbreviation
          }
        }
      }
    }
  }
}
