query getRatingsForStudentStandardsGradebook($studentId: ID!, $filtersForGeneric: ibPYPElementRatingFiltersForGeneric) {
  node(id: $studentId, type: STUDENT) {
    id
    ... on Student {
      id
      ibPYPElementRatings(dataSet: STANDARD_CALCULATED_RATING, filtersForGeneric: $filtersForGeneric) {
        id
        ibPYPElementId
        ibPYPElementType
        academicCriteriaSet {
          id
        }
        academicCriteriaValue {
          id
          color
        }
        isComputedRating
        isMasteryRating
        value
        percentValue
      }
    }
  }
}
