query getStaffGrades($id: ID!, $filters: AllGradesFilters!, $academicYears: [ID!]) {
  node(id: $id, type: STAFF) {
    id
    ... on Staff {
      id
      allGrades(filters: $filters) {
        unitPlanCount(academicYears: $academicYears)
        curriculumProgram {
          ...curriculumProgramBasicDetailsItem
        }
        ...gradeItem
      }
    }
  }
}

query getAiConverstion($id: ID!) {
  node(id: $id, type: AI_CONVERSATION) {
    ... on AiConversation {
      id
      messages {
        totalCount
        edges {
          node {
            id
          }
        }
      }
    }
  }
}

query getAiConverstion($id: ID!) {
  node(id: $id, type: AI_CONVERSATION) {
    ... on AiConversation {
      id
      messages {
        totalCount
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
