query getStaffYardDutySlots($id: ID!, $yardDutyFilters: YardDutySlotFilter) {
  node(id: $id, type: STAFF) {
    id
    ... on Staff {
      id
      yardDutySlots(filters: $yardDutyFilters) {
        date
        day
        startTime
        endTime
        isSelected
        yardDuty {
          id
          label
          location {
            id
            label
            abbreviation
          }
        }
        teachers {
          staff {
            id
            profileImage
            ...staffNameFields
          }
          type
        }
      }
    }
  }
}
