query getStaffYardDuties($id: ID!, $academicYearId: ID, $yardDutyFilters: YardDutySlotFilter) {
  node(id: $id, type: STAFF) {
    ... on Staff {
      id
      yardDutySlots(filters: $yardDutyFilters) {
        date
        day
        teachers {
          staff {
            id
            firstName
            middleName
            lastName
            profileImage
            isArchived
            isArchivedV2(filters: {academicYearId: $academicYearId})
          }
          type
        }
        isSelected
        yardDuty {
          id
          label
          location {
            id
            label
            abbreviation
          }
        }
        startTime
        endTime
      }
    }
  }
}
