query getWorkbookSchoolTemplateQueryV2($types: [ORGANIZATION_RESOURCE_TYPE_ENUM!], $organizationId: ID!, $curriculumProgramId: ID!, $searchText: String!, $first: Int, $after: String, $status: ORGANIZATION_RESOURCE_STATUS_ENUM, $states: [ORGANIZATION_RESOURCE_STATE_ENUM!], $courseIds: [ID!], $createdBy: [ID!]) {
  node(id: $organizationId, type: ORGANIZATION) {
    id
    ... on Organization {
      workbookTemplatesV2(curriculumProgramId: $curriculumProgramId) {
        isSuccess
        warning
        workbookTemplateResource {
          ...workbookTemplateResourceBasicDetailsItem
        }
      }
    }
  }
}

query getStudentAlertTypes($id: ID!) {
  node(id: $id, type: STUDENT) {
    ... on Student {
      id
      alertTypes {
        id
        name
        icon
      }
    }
  }
}

query getStudentAlertTypes($id: ID!) {
  node(id: $id, type: STUDENT) {
    ... on Student {
      id
      alertTypes {
        id
        name
        icon
      }
    }
  }
}
