query getSchoolEventsFeed($input: CalendarEventsFeedInput!) {
  platform {
    calendarEventsFeed(input: $input) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          label
          isFullDayEvent
          startDateTime
          endDateTime
          eventTag {
            id
            label
            colorCode
          }
          parentEvent {
            id
          }
          createdAt
          createdBy {
            id
            firstName
            lastName
            profileImage
          }
          associatedEntities {
            __typename
            ... on GenericCurriculumProgram {
              id
              programType
              students {
                totalCount
              }
              staff {
                totalCount
              }
              familyMembers {
                totalCount
              }
            }
          }
          metadata {
            recurrenceType
          }
          recurringSetting {
            frequency
            weekDays
            interval
            endDate
            monthDays
            setPositions
            count
            timezone
          }
        }
      }
    }
  }
}
