query getStudentAssessmentToolNodeDetails($id: ID!, $type: ENTITY_TYPE_ENUM!) {
  node(id: $id, type: $type) {
    id
    ... on Rubric {
      ...rubricItem
    }
    ... on Checklist {
      ...checklist
    }
    ... on SinglePointRubric {
      ...singlePointRubricItem
    }
    ... on Exemplar {
      ...exemplarItem
    }
    ... on Anecdote {
      ...anecdoteItem
    }
    ... on MypObjectiveRubric {
      ...mypObjectiveRubricItem
    }
    ... on StandardRubric {
      ...standardRubricItem
    }
    ... on GenericRubric {
      ...genericRubricItem
    }
    ... on GradeScaleEntityDetail {
      ...gradeScaleEntityDetailsItem
    }
  }
}
