query getStudentTasks($userId: ID!, $studentIds: [ID!], $filters: TaskFilter, $first: Int, $after: String, $orderByDirection: ORDER_BY_DIRECTION, $type: ENTITY_TYPE_ENUM!) {
  node(id: $userId, type: $type) {
    id
    ... on Student {
      id
      tasks(filters: $filters, first: $first, after: $after, orderByDirection: $orderByDirection) {
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
        edges {
          id
          orderDate
          itemType
          item {
            id
            ... on StudentAssignment {
              ...studentAssignmentItem
            }
            ... on ProjectDeadline {
              ...projectDeadlineItem
            }
            ... on ProjectTaskResponse {
              id
              project {
                id
                projectGroup {
                  id
                  type
                  subType
                  courses {
                    edges {
                      node {
                        id
                      }
                    }
                  }
                }
              }
              task {
                ...projectGroupTaskItem
              }
              latestSubmissionResponse {
                id
                status
              }
            }
          }
        }
      }
    }
    ... on FamilyMember {
      id
      tasks(filters: $filters, first: $first, after: $after, studentIds: $studentIds, orderByDirection: $orderByDirection) {
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
        edges {
          id
          orderDate
          itemType
          item {
            id
            ... on StudentAssignment {
              ...studentAssignmentItem
            }
            ... on ProjectDeadline {
              ...projectDeadlineItem
            }
            ... on ProjectTaskResponse {
              id
              project {
                id
                projectGroup {
                  id
                  type
                  subType
                  courses {
                    edges {
                      node {
                        id
                      }
                    }
                  }
                }
              }
              task {
                ...projectGroupTaskItem
              }
              latestSubmissionResponse {
                id
                status
              }
            }
          }
        }
      }
    }
  }
}

fragment learnerPortfolioItem on LearnerPortfolio {
  id
  isArchived
  yearGroup {
    id
    name
    grade {
      id
      name
    }
  }
  studentLearnerPortfolios {
    totalCount
  }
}
