query getStudentRatingDetail($id: ID!, $filtersForGeneric: ibPYPElementRatingFiltersForGeneric) {
  node(id: $id, type: STUDENT) {
    id
    ... on Student {
      ...userNameFields
      profileImage
      registrationCategory
      ibPYPElementRatings(dataSet: PROJECT_ASSESSMENT, filtersForGeneric: $filtersForGeneric) {
        id
        value
        ibPYPElementId
        isComputedRating
        academicCriteriaSet {
          id
          criteriaType
        }
        academicCriteriaValue {
          id
          label
          abbreviation
        }
        parent {
          id
          ... on Project {
            projectGroup {
              id
              type
            }
          }
        }
      }
    }
  }
}
