query getSchoolEventsFeed($input: CalendarEventsFeedInput!) {
  platform {
    calendarEventsFeed(input: $input) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          label
          isFullDayEvent
          startDateTime
          endDateTime
          eventTag {
            id
            label
            colorCode
          }
          parentEvent {
            id
          }
          associatedEntities {
            ... on GenericCurriculumProgram {
              id
              programType
            }
          }
          metadata {
            recurrenceType
          }
          recurringSetting {
            frequency
            weekDays
            interval
            endDate
            monthDays
            setPositions
            count
            timezone
          }
        }
      }
    }
  }
}
