mutation importCourseFlowResource($input: ImportLearningCourseFlowResourceInput!, $assessmentAssignmentsFilters: AssessmentAssignmentsFilters, $studentIds: [ID!], $skipAssignedStudents: Boolean! = true, $stateFilters: LearningCourseFlowStateFilter, $filters: LearningCourseFlowFilter, $syncedBluePrintItemFilters: SyncedBluePrintItemFilter, $assessmentFieldUids: [String!], $includeCourseSyncStatus: Boolean = false) {
  planner {
    importLearningCourseFlowResource(input: $input) {
      isSuccess
      error
      courseFlowResource {
        ...courseFlowResource
      }
    }
  }
}
