fragment projectResolvedFieldValueItem on ResolvedFieldValue {
  id
  type
  ... on ResolvedFieldBenchmarkSet {
    id
    benchmarks {
      ...benchmarkItem
    }
  }
  ... on ResolvedFieldConceptSet {
    id
    concepts {
      ...conceptItem
    }
  }
  ... on ResolvedFieldActionSet {
    id
    actions {
      ...actionItem
    }
  }
  ... on ResolvedFieldLPSet {
    id
    learnerProfiles {
      ...lpItem
    }
  }
  ... on ResolvedFieldThemeSet {
    id
    themes {
      ...themeItem
    }
  }
  ... on ResolvedFieldSubjectSet {
    id
    subjects {
      ...subjectItem
      subjectGroup {
        id
        name
        constants
        globalSubjectGroup {
          id
          name
          constants
        }
      }
    }
  }
  ... on ResolvedFieldATLSet {
    id
    atls {
      ...atlItem
    }
  }
  ... on ResolvedFieldRelatedConceptSet {
    id
    relatedConcepts {
      ...relatedConceptItem
    }
  }
  ... on ResolvedFieldVideoAttachment {
    id
    attachment {
      ...attachmentItem
    }
  }
  ... on ResolvedFieldStudentTemplate {
    id
    attachmentGroups {
      ...attachmentGroupItem
    }
  }
  ... on ResolvedFieldTags {
    id
    tags {
      id
      label
    }
  }
  ... on ResolvedFieldGenericTags {
    id
    genericTags {
      id
      label
      abbreviation
      __typename
    }
    __typename
  }
  ... on ResolvedFieldPlannerElementSet {
    id
    type
    nodes {
      ...projectPlannerElementNodeItem
    }
  }
  ... on ResolvedFieldSubjectGroup {
    id
    type
    subjectGroups {
      ...subjectGroupWithGlobalSubjectGroupItem
    }
  }
  ... on ResolvedFieldScore {
    ...fieldScoreItem
  }
  ... on ResolvedFieldObjectiveLevel {
    id
    nodes {
      id
      label
      dataSetNodeWrapper {
        properties {
          subjects {
            id
          }
        }
      }
    }
  }
  ... on ResolvedFieldAttachments {
    id
    type
    attachments {
      ...attachmentItem
    }
  }
}

fragment learnerPortfolioItem on LearnerPortfolio {
  id
  isArchived
  yearGroup {
    id
    name
    grade {
      id
      name
    }
  }
  studentLearnerPortfolios {
    totalCount
  }
}
