fragment postItem on Post {
  id
  title
  attachments {
    ...attachmentItem
    displaySequence
  }
  createdBy {
    ...userItem
  }
  createdAt
  publishedAt
  comments {
    totalCount
    unreadCount
  }
  likes {
    totalCount
    edges {
      node {
        ...likeItem
      }
    }
  }
  seen {
    totalCount
    edges {
      node {
        ...postSeenItem
      }
    }
  }
  state
  course {
    id
    title
  }
  students {
    totalCount
    edges {
      node {
        ...studentItem
      }
    }
  }
  isPrivate
  isHiddenFromStudents
  items {
    item {
      ... on StudentTemplateResponse {
        id
        metadata
        template {
          id
          fields {
            id
            label
            placeholder
            type
            metadata
            dataSets {
              title
              type
              values {
                value
                date
                displaySequence
                id
                item {
                  id
                  itemName
                }
              }
            }
          }
        }
        individuallyRated
        student {
          ...studentItem
        }
        fields {
          id
          value
          uid
          resolvedMinimalTree {
            id
            type
            ... on ResolvedFieldAttachmentGroup {
              attachmentGroups {
                id
                displaySequence
                metadata
                attachments {
                  id
                  type
                  url
                  displaySequence
                }
              }
            }
          }
        }
        ...routineLikesAndComments
      }
    }
    itemType
  }
}

fragment notificationItem on Notification {
  id
  type
  primaryEntity
  isNew
  isRead
  metadata
  category
  createdBy {
    id
    firstName
    lastName
    middleName
    profileImage
    type
    profileImage
    ... on Student {
      preferredName
      pronouns
      suffix
    }
  }
  createdAt
  updatedBy {
    id
    firstName
    lastName
    middleName
    profileImage
    ... on Student {
      preferredName
      pronouns
      suffix
    }
  }
  course {
    ...courseItem
    grades {
      id
      name
    }
    curriculumProgram {
      id
      type
    }
  }
  courses {
    id
    title
    curriculumProgram {
      id
      type
    }
  }
  updatedAt
  contextData {
    ... on Grade {
      id
      name
    }
    ... on Course {
      id
      title
      learningCourse {
        id
        title
        academicCourse {
          id
          label
        }
      }
    }
    ... on YearGroup {
      id
      name
    }
    ... on Student {
      id
      firstName
      lastName
      middleName
      type
      preferredName
      pronouns
      suffix
    }
    ... on BehaviourIncident {
      id
      uid
      category {
        id
        rootCategory {
          id
          name
        }
      }
    }
  }
  messageData
  extensionType
  extensionData
}
