fragment organizationItem on Organization {
  id
  subjects(filters: $filters) {
    ...subjectItem
  }
}

fragment userMapItem on CourseUserMapConnection {
  edges {
    node {
      id
      user {
        ... on Student {
          id
          firstName
          middleName
          lastName
          preferredName
          prefix
          suffix
          pronouns
          type
          isArchived
          isArchivedV2(filters: {academicYearId: $academicYearId})
          profileImage
          yearGroup {
            id
            name
          }
          alertTypes {
            ...alertTypeFields
          }
        }
      }
      tags {
        id
        label
      }
    }
  }
}
