fragment progressReportsConnection on StudentProgressReportConnection {
  totalCount
  pageInfo {
    hasNextPage
    endCursor
  }
  edges {
    node {
      ...progressReport
    }
  }
}

fragment attachmentEvidenceItem on Attachment {
  id
  type
  title
  streamUrl
  url
  signedUrl
  name
  mimeType
  thumbUrl
  description
  metadata
  resolvedParentEntity {
    ... on AttachmentGroup {
      resolvedParentEntity {
        ... on StudentAssignmentSubmission {
          id
          assignment {
            id
            assignedStudents {
              id
              submission {
                id
              }
            }
          }
        }
      }
    }
  }
}
