fragment projectGroupSupervisorApprovalInfoItem on ProjectGroupSupervisor {
  id
  staff {
    ...supervisorInfo
    role
    otherDetails {
      id
      organizationName
      phoneNumber
    }
    isArchived
    isArchivedV2(filters: {academicYearId: $academicYearId})
    isArchivedFromCurriculum(filters: $supervisorArchivedFilters)
    curriculumPrograms {
      id
      acronym
    }
  }
  approvalStatus
  invitedBy {
    ...userNameFields
    profileImage
    ... on Student {
      alertTypes {
        ...alertTypeFields
      }
    }
  }
}
