fragment questionItem on Question {
  id
  difficulty
  questionType {
    id
    uid
    config
  }
  libraryUid
  questionScore
  updatedAt
  metadata
  presetQuestionId
  assessmentTools {
    totalCount
    edges {
      node {
        ...questionAssessmentToolItem
      }
    }
  }
  fields {
    ...questionFieldsItem
  }
  answerFields {
    ...questionFieldsItem
  }
  librarySubjects {
    id
    label
  }
  associatedEntities {
    id
    ... on Subject {
      id
      name
    }
    ... on GenericTag {
      id
      label
    }
    ... on PlannerElementNode {
      id
      label
      depth
    }
  }
}
