query getUserEnrolledPeriodsV3($id: ID!, $type: ENTITY_TYPE_ENUM!, $periodFilters: PeriodFilterOptions) {
  node(id: $id, type: $type) {
    ... on Student {
      ...studentPeriodListItem
    }
    ... on Staff {
      ...staffPeriodListItem
    }
  }
}

fragment studentPeriodListItem on Student {
  id
  ...studentNameFields
  enrolledPeriodsV3(filters: $periodFilters) {
    ...selectedPeriodItem
  }
}

fragment courseItem on Course {
  id
  title
  isArchived
  primaryGrade {
    id
    curriculumProgram {
      id
      type
    }
  }
  grades {
    id
  }
}

fragment periodItem on Period {
  id
  label
  type
  isDefault
  startTime
  endTime
  sequence
  isDefault
  abbreviation
}

fragment staffItem on Staff {
  id
  ...staffNameFields
  profileImage
  email
  showPitchScreen
  role
  showClassSelectionScreen
  showBifurcationScreen
  isDevUser
  isArchived
  entityTags {
    id
    key
    value
  }
}

fragment staffPeriodListItem on Staff {
  id
  ...staffNameFields
  enrolledPeriodsV3(filters: $periodFilters) {
    ...selectedPeriodItem
  }
}

fragment selectedPeriodItem on TimetableSlotV2 {
  date
  isSelected
  day
  rotationEntity {
    id
    label
  }
  location
  course {
    ...courseItem
  }
  period {
    ...periodItem
    abbreviation
  }
  teachers {
    staff {
      ...staffItem
    }
  }
  subject
  startTime
  endTime
}
