mutation studentTransferScheduleBatch($input: StudentTransferScheduleBatchInput!) {
  platform {
    studentTransferScheduleBatch(input: $input) {
      isSuccess
      warning {
        code
        message
        duplicates
        missing
        driftedIds
        failures {
          key
          message
        }
        offendingIds {
          id
          status
        }
        transferRequestId
      }
      studentTransferRequests {
        id
        uid
        status
      }
    }
  }
}
