fragment unitPlanItem on OrganizationResource {
  id
  label
  displaySequence
  depth
  resourceType
  state
  attachment {
    ...attachmentItem
  }
  item {
    ... on Assessment {
      ...completeAssessmentDetails
    }
    ... on OrganizationResource {
      id
      attachment {
        ...attachmentItem
      }
    }
  }
  parentResource {
    id
  }
  childrenHierarchyInfo(filters: $filters) {
    maxDepth
    totalCount
    totalCountWithFolder
  }
}

query getAssessmentMultiNode($ids: [ID!]) {
  multiNode(ids: $ids, type: ASSESSMENT) {
    id
    ... on Assessment {
      ...completeAssessmentDetails
    }
  }
}
