mutation updateGenericRubricDescriptors($input: [UpdateGenericRubricDescriptorInput!]) {
  planner {
    updateGenericRubricDescriptors(input: $input) {
      isSuccess
      warning
      response {
        id
        label
        description
        displaySequence
        score
        gradeScaleValue {
          id
          label
          description
          abbreviation
          displaySequence
        }
        standardGradeScaleValueDescriptor {
          id
          description
          gradeScaleValue {
            id
            label
            description
            abbreviation
            displaySequence
          }
        }
      }
    }
  }
}
