query getOrganizationStudentsFeed($filters: OrgConnectionFilterInput, $yearGroupAcademicYearMapFilters: YearGroupAcademicYearFilters, $userArchivedFilters: UserArchivedFilters) {
  platform {
    organization {
      id
      students(filters: $filters) {
        totalCount
        edges {
          node {
            id
            email
            firstName
            middleName
            lastName
            pronouns
            preferredName
            prefix
            suffix
            type
            profileImage
            isArchived
            isArchivedV2(filters: $userArchivedFilters)
            curriculumProgram {
              id
              type
            }
            yearGroup {
              id
              name
              curriculumProgram {
                id
                type
              }
            }
            yearGroupAcademicYearMap(filters: $yearGroupAcademicYearMapFilters) {
              ...yearGroupAcademicYearMapDetails
            }
          }
        }
      }
    }
  }
}

fragment yearGroupAcademicYearMapDetails on YearGroupAcademicYearMap {
  academicYear {
    id
    isCurrentAcademicYear
    isUpcomingAcademicYear
    isPreviousAcademicYear
  }
  yearGroup {
    id
    name
    curriculumProgram {
      id
      acronym
    }
  }
}
